### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by msabramo** [jmorrell/atom-jump-to-line#2]
**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**jump-to-line Version**: 0.2.0

I'm invoking from the Command Palete:

![screenshot 2017-01-24 10 16 31](https://cloud.githubusercontent.com/assets/305268/22260502/50855802-e21e-11e6-84f7-fae640d82a37.png)

but no labels show up.

No error messages in the Developer Tools Console.

**Comment by jmorrell** [comment]
Sorry, I'm out of the country at the moment with limited bandwidth. I'll take a look at this when I get back to the land of high-speed internet and free time :)

Thanks for reporting! 👍

**Comment by jmorrell** [comment]
Fixed by https://github.com/jmorrell/atom-jump-to-line/commit/8d4672b85a9e9c6652c710de6918ef981f159cec 

Published the new version 😄
